### ISSUE TITLE
Can we  skip `appendAssign` in `xxxs:=append(yyys,z)`？

### ISSUE THREAD

**Issue by edocevol** [go-critic/go-critic#1446]

**Comment by quasilyte** [comment]
Can you show the code where it's an intended behavior?

**Comment by cristaloleg** [comment]
Sounds like a problem can be fixed by disabling a check.

**Comment by edocevol** [comment]
```go
// BatchMoveEntries 批量移动条目
type BatchMoveEntries struct {
  ParentEntryID string
  AfterID       string
  EntryIDs      []string
}
-----
var (
  err     error
  entries []*entity.Entry
  parents []*entity.Entry
)

entriesID := append(cmd.EntryIDs, cmd.ParentEntryID)
err = db.Where("id in (?)", entriesID).Error;
```

We want to query all entries, but I do not want to change origin cmd.EntryIDs

**Comment by quasilyte** [comment]
The problem with that is it's extremely error-prone to unexpected long-reaching side-effects that depend on a hard to maintain fact that `cmd.EntryIDs` cap is exactly the same as its length. Otherwise no new slice will be created and both slices will share the same memory region. Here is an illustration:
https://go.dev/play/p/2gQYTw_Bw-n

If you really want a new slice and specifically want to avoid changing the origin slice, why not make a real copy yourself and avoid the error-prone surface?
```
entries := make([]*entity.Entry, 0, len(cmd.EntriIDs+1)
entries = append(entries, cmd.EntriIDs...)
entries = append(entries, cmd.ParentEntryID)
```
This code is safe  100% time. You might also use a `copy` function in some cases.

**Comment by cristaloleg** [comment]
💯 for an explicit copy. Have a similar code in my codebase and did a copy to make it bug-prone.

**Comment by edocevol** [comment]
Thank you for your answer. I got it.
