### ISSUE TITLE
cmd/critisize/main.go:54 update usage

### ISSUE THREAD

**Issue by fexolm** [go-critic/go-critic#191]
`s/usage: gocritic [flags] [package]/usage: gocritic check-package [flags] [package]`

**Comment by Quasilyte** [comment]
For a temporary fix, replacing usage string will do.
For a better fix, we should figure out how to do proper message printing from sub-commands.
Maybe `log.SetPrefix` in `gocritic` and then using `log` package instead of `fmt.*`?
This way, if gocritic executed from test (for example), it will not print `gocritic check-package: ` prefix, but when it's executed from `gocritic`, it will print sub-command path before the message.
