### ISSUE TITLE
lint/lenNil: detect redundant x!=nil before len(x)

### ISSUE THREAD

**Issue by cristaloleg** [go-critic/go-critic#291]
Before:
```go
if myMap != nil && len(myMap) == smth { 
```
After:
```go
if len(myMap) == smth { 
```
See: https://golang.org/pkg/builtin/#len

**Comment by Quasilyte** [comment]
So, gosimple does cover slices, but not maps?

**Comment by Quasilyte** [comment]
https://play.golang.org/p/tqRqMj_7TG2

We may want to contact Dominikh for this.
At the very least it would be a right thing to create an issue on gosimple and suggest improvement.
We can provide implementation until he improves gosimple.
And since we're not practicing checkers removal, our implementation may stay as well (at least for some time).

**Comment by cristaloleg** [comment]
After this comment I'm in doubt that checker is needed at all
https://github.com/go-critic/go-critic/pull/293#issuecomment-399488071
