### ISSUE TITLE
cmd/criticize: add `-disable` flag that turns off specified checks

### ISSUE THREAD

**Issue by fexolm** [go-critic/go-critic#294]
Now, if user needs to disable one checker he should enable all besides one.

**Comment by Quasilyte** [comment]
Hmm. Maybe we should reconsider `-withExperimental` and `-withOpinionated` then?
We can have "classes" for `-disable` like we have special argument for `-enable` ("all").
Default value for `-disable` would be `experimental,opinionated`.
So, we filter-out disabled list, then enable ones from `-enable` list.
In case of `-enable="all" -disable="experimental,opinionated"` (default values) we get current behavior.
`-enable=all -disable=""` does enable everything.

**Comment by Quasilyte** [comment]
Personally, I don't find `-disable` useful.
Question is: why do you need that?
If you're doing CI-like script and trying to disable one checker, just do an explicit `-enable` list, like with `gometalinter`. The rationale behind that it makes your config stable for different versions of the linter, even if there are new checkers, they will not be enabled accidentally. 
If you do disable 2 checkers with `-disable=x,y`, next gocritic release may break your build due to new checkers.

I'll not convinced until real use case is described.

**Comment by Quasilyte** [comment]
@cristaloleg, whats your thoughts on this?

**Comment by cristaloleg** [comment]
IMO we should add ‘-disable’ flag. Typing all rules except one is an overkill, at least for me.
Your last point ditectly towards to adding this flag :) (regarding carefully built ‘-enable’)
Regarding withExperimenatal & withVeryOpinionated - I’m not sure how to incorporate them in this change.

**Comment by Quasilyte** [comment]
OK.

But it would be good to see solution that addresses both existing `-with` flags (removes/replaces/etc) them and doesn't make other use cases impossible or more complicated.

**Comment by Quasilyte** [comment]
@cristaloleg, but my question was about why one may need to disable 1 or 2 checkers.
It won't work for CI.
You could probably tell something about "we can't satisfy all gophers by our default opinionated set",
but it also needs explanation, because the point of linter is to enforce something.
We have "escape hatch" like `-enable` list that makes custom list possible.
