### ISSUE TITLE
lint: ifElseChain: should rewrite if-else to switch statement, maybe overzealous?

### ISSUE THREAD

**Issue by jawr** [go-critic/go-critic#453]
This was the code: 

```
if groups[0].ID == 1 {
    g = groups[0]
    ng = groups[1]
} else if groups[1].ID == 1 {
    g = groups[1]
    ng = groups[0]
} else {
    return nil
}
```

Is there really a need to switch on this? I did change it to `switch 1 { case groups[0]: ...` just to appease it though.

**Comment by Quasilyte** [comment]
This is a style check that is based on Go style guide.
https://golang.org/doc/effective_go.html#switch

> It's therefore possible—and idiomatic—to write an if-else-if-else chain as a switch. 

As all style checks, it's possible to avoid advice completely.
You can turn off that particular check with `-disable=ifElseChain`, for example, or use explicit `-enable` list to include only those checks that make sense for you.

go-critic tries to be inclusive for any at least somewhat useful checks, leaving the user to decide whether they make sense for them. 

There is default set that is enabled by default, but even it may cause some disagreement.
This is true for most style guides.

**Comment by Quasilyte** [comment]
By the way, I would re-write it like this:
```go
switch {
case groups[0].ID == 1:
  g = groups[0]
  ng = groups[1]
case groups[1].ID == 1:
  g = groups[1]
  ng = groups[0]
default:
  return nil
}
```
To preserve initial flow style. `switch 1` is fragile in case you may want to add more checks or compare with a different value. But this is up to you, of course.

**Comment by jawr** [comment]
Ah that is indeed much nicer, thank you for the response.

So far really liking the advice given!

**Comment by jesseduffield** [comment]
@quasilyte I've just come across this issue myself. I'm wondering in which situations it is appropriate to use an if-else-if-else structure? If the answer is never, that begs the question of why is the else-if syntax included in the language.

I would like to have go-critic only tell me to use a switch statement if in each condition we're checking the value of the one variable. I feel like the switch statement's expressiveness is diluted if we're arbitrarily using it everywhere we would otherwise use if-else-if-else.

**Comment by quasilyte** [comment]
> I'm wondering in which situations it is appropriate to use an if-else-if-else structure? If the answer is never, that begs the question of why is the else-if syntax included in the language.

Goto is also included in the language. It's sometimes useful. You can almost always avoid it and it's a good practice to do so. There are other things that are questionable: bare/naked returns, for instance.

To answer you question directly: it's not **never**. `go-critic` actually allows the simple if-else/elseif things, where you have only 1 elseif part. If you have more, it's essentially a switch anyway. Effective Go suggests to use switches as a replacement for such elseif chains.

If you don't like it that much, I would suggest turning off this diagnostic.

> I feel like the switch statement's expressiveness is diluted if we're arbitrarily using it everywhere we would otherwise use if-else-if-else.

Don't get me wrong, personal experience and opinions do matter. But there is also a source that is quite respectable and since this diagnostic basically implements it, I see no rationale in sharing personal opinions here because it "works as intended". There is no bug here. If you don't like it, you can turn it off locally, so other people can use the Effective Go advice. Sounds fair?

`go-critic` includes a lot of checkers. Not every one of them is for everyone. If you're using `golangci-lint`, I would suggest having an explicit checkers list for a `go-critic`. Example: https://github.com/VKCOM/noverify/blob/f6952acf033ce1cbbbd5ca219da8969d97a6af2d/.golangci.yml#L43-L111

We could theoretically add a flag that would make `ifElseChain` only report cases where you can use a tag-based structure. But it's a separate issue and you could probably open a ticket that asks specifically for that (if you're going to use it, of course).

**Comment by jesseduffield** [comment]
@quasilyte thanks for the thorough, well reasoned response :)

**Comment by jsumners** [comment]
```go
if bool1 && bool2 {
  // do something when both are true
} else if bool1 {
  // do something when 1 is true
} else if bool2 {
  // do something when 2 is true
}
```

That will violate this rule and the linter will ask that you refactor it into a `switch` statement. This is impossible given that the check is on the state of two items instead of a single one.

**Comment by quasilyte** [comment]
```go
switch {
case bool1 && bool2:
  // do something when both are true
case bool1:
  // do something when 1 is true
case bool2:
  // do something when 2 is true
}
```
@jsumners

**Comment by jsumners** [comment]
Very strange. Thanks.

**Comment by jdemeyer** [comment]
> Effective Go suggests to use switches as a replacement for such elseif chains.

The actual quote is `It's therefore possible—and idiomatic—to write an if-else-if-else chain as a switch.`

So yes, it's suggested but not more than that. I certainly don't read it as "you should replace all if-else chains with 3 or more blocks with switch" which is what `gocritic` seems to suggest.

In my mind, the main *conceptual* difference between an `if-else` chain and a `switch` is whether the order matters. So I see an `if-else` chain as a procedure to follow from top to bottom, while a `switch` is like a set of independent cases. But maybe that's just me...

> Or you can use a #diagnostic tag to enable only bug-related checks and avoid style checks. ifElseChain is a #style checker.

Very much :+1: for this. I completely disagree with this specific `ifElseChain` lint check, but thanks to these tags, I can still use the other `gocritic` checks.

**Comment by cristaloleg** [comment]
> while a switch is like a set of independent cases

https://go.dev/play/p/qUNkwA9__eF

From Go spec:

> In an expression switch, the switch expression is evaluated and the case expressions, which need not be constants, are evaluated left-to-right and top-to-bottom; the first one that equals the switch expression triggers execution of the statements of the associated case

https://go.dev/ref/spec#Switch_statements

(however, for type switch this might be somewhat misleading, see https://go-critic.com/overview.html#caseorder)

**Comment by jdemeyer** [comment]
Right, I know what the spec says, but that's not what I meant. I meant that _style-wise_ I find it more logical to use `switch` for independent cases and an `if-else` chain when the order matters.

**Comment by sjay-lyft** [comment]
When is this check ever advantageous?

**Comment by cristaloleg** [comment]
See above

**Comment by sjay-lyft** [comment]
As far as I can tell, there is zero difference in the logic or final outcome between an `if ... else if ... else ...` block and a `switch case ... case ... default ...` block. What is considered an "idiom" is entirely subjective.

So why enforce an arbitrary rule that has zero objective benefit? Please correct me if I'm missing some difference in logic or final outcome here. 

As someone else wrote above, why ban using `if ... else if ... else ...` if it's a feature of Go and many other programming languages?

**Comment by cristaloleg** [comment]
> So why enforce an arbitrary rule that has zero objective benefit?

where is the enforcement? check can be easily disabled if you diagree.

**Comment by sjay-lyft** [comment]
Right. But why is it enforced by default? And why does it exist in the first place, per my comment above?

**Comment by sjay-lyft** [comment]
To be clear, I think this is a fantastic library. But this seems like a totally pointless rule that impedes developer productivity, for the reasons I gave above.

**Comment by cristaloleg** [comment]
> why is it enforced by default?

For me `enforced` sounds somewhat intrusive, let's say `enabled`. 

Well, the motivation is simple: me and @quasilyte found that in most of the cases switch leads to a simpler code with less `{` and `}`. Also, we checked switch usage across Go codebase and haven't found cases where it makes code worse. So, here it is.

**Comment by sjay-lyft** [comment]
> Well, the motivation is simple: me and @quasilyte found that in most of the cases switch leads to a simpler code with less { and }.

That's true, but it also adds a line relative to using an `if ... else if ... else ...` block because the line with the `switch` statement must be added. So again, this matter is subjective and there is no objective benefit; in fact, one can argue it needlessly complicates the code by adding a line. That's why I say this check shouldn't be enabled by default but should be something that one can optionally enable.

As @jdemeyer posted above, the style guide does not say that using a `switch` statement is preferred to using an `if ... else if ... else ...` block, but only that it's possible.

**Comment by quasilyte** [comment]
@sjay-lyft well, then don't use this checker, gocritic is configurable.
