### ISSUE TITLE
How should one fix appendAssign?

### ISSUE THREAD

**Issue by akshaymankar** [go-critic/go-critic#865]
I have some code which looks like this:

```golang
var command []string
if someCondition 
 command = append(something.InitProcess, something.Launch)
} else {
 command = []string{"something"}
}
```
go-critic reports `appendAssign: append result not assigned to the same slice (gocritic)`. 
I do not wish to mutate `something.InitProcess`.  Is there any other way to resolve this?

Thanks,
Akshay && @alex-slynko

**Comment by quasilyte** [comment]
There are few cases of valid appends to a different slice, but they should be carefully used, since appending to as slice might extend it's capacity or might overwrite aliased elements that are shared via slice variables.

Sometimes it's better to do a copy instead of using append to existing slice, to avoid **any** mutations to the append 1st argument. In the example above that you provided, the original slice underlying memory will change. If this is not a hot path, I would create a copy and append to a copied slice instead.

But back to the topic:
```
	// More verbose, but more explicit. Fixes the warning.
	var command []string
	if someCondition {
		command = something.InitProcess
		command = append(command, something.Launch)
	} else {	
		command = []string{"something"}
	}
		
	// Same amount of SLOC, but less obvious.
	command := something.InitProcess
	if someCondition {
		command = append(command, something.Launch)
	} else {
		command = []string{"something"}
	}
```

Both examples operate in the same way as your example.

A better example would be factoring this code into a function, so you don't have to give any name to it:

```go
func makeCommand(someCond bool, something T) []string {
	if someCondition {
		return append(something.InitProcess, something.Launch)
	}
	return []string{"something"}
}
```

The other way is to disable `appendAssign` check from your pipeline if it blocks you.

`appendAssign` addresses 2 issues:
* Marks `append` that behaves in a way that is not intuitive for all gophers. Code can usually be re-written more explicit.
* Typos in a code that has several similar slices where it's easy to misprint src/dst/s1/s2 append argument (while types would still match).

It also encourages slice copying in this scenario.

Hope this helps.

**Comment by quasilyte** [comment]
Does it answer your question?

**Comment by akshaymankar** [comment]
Yes, thank you.
