### ISSUE TITLE
Feature request : check flag to enable all checker

### ISSUE THREAD

**Issue by bytemare** [go-critic/go-critic#912]
Hi!

I very much like the tool and checkers, and I am impressed by all the work put into it. Congrats guys, and thank you very much for it.

I mainly use it with golangci-lint, and want to enable all the checkers. This results in a long configuration file, and that is another thing to maintain.

I think it would be useful to add a flag when invoking gocritic that simply enables all the checkers. What do you think ?

**Comment by quasilyte** [comment]
Hello!

There is `-enableAll` flag that enables all checkers.

And because of the `-disable` filters  are applied after the `enable`-related flags, you can filter-out things you don't want to include.

For example, `gocritic check -enableAll ./src/...` enables everything.
```bash
# All checkers except ones tagged with "experimental" tag
$ gocritic check -enableAll -disable '#experimental' ./src/...

# All checkers without "opinionated" and "experimental" tag.
# Also excludes an "unslice" checker.
$ gocritic check -enableAll -disable '#opinionated,#experimental,unslice' ./src/...
```
I'm not sure whether you can use it through golangci-lint. If it doesn't include it, maybe we can make a pull request that adds it.

To see checker-related tags:
```bash
$ gocritic doc
gocritic doc
appendAssign [diagnostic]
appendCombine [performance]
argOrder [diagnostic experimental]
assignOp [style]
(... and others)
```

Is that the kind of functionality you're describing?

**Comment by bytemare** [comment]
Hi !

Thank you very much for your answer 😃 You were right, and I also found the other way to do it. Thanks again for your work !!!

---

I failed to see this flag in the doc / Readme, even though it's there. My bad, I'm sorry.

Concerning golangci-lint, the way to enable all linters is to add in the ` .golangci-lint.yml` file :
```
linters-settings:
    ...
    gocritic:
        enabled-tags:
          - diagnostic
          - experimental
          - opinionated
          - performance
          - style
```

I should have read the docs more thoroughly !
